serviceRealm: MUSS-1

chat:
  prefix: '§7[§l§bi§7] '
  messages:
    congr-send: 'Поздравление было отправлено.'
    congrats: '§e%SENDER% поздравил вас с повышением уровня!'
    global-level-message: '§cВНИМАНИЕ! §e%NAME% достигнул уровня §b%LEVEL%§e, поздравить /congr %NAME%'
    box-recieved: '§fВы принесли груз, ожидайте продажи! §eСписок товаров:'
    wagon-copy: 'Вы уже заказывали доставку продуктов, заберите её.'
    no-product: '§fВ продуктовой лавке, закончился товар. Закажите его в меню. §e(КЛИК СЮДА)'
    box-taken: 'Вы получили заказанные продукты.'
    collector-income: '§fСборщик монет собрал §e+%INCOME%'
    sell-product: '§fПродуктовая лавка продала §b%TITLE%§f, прибыль §e+%COST%$'
    wagon-buy: 'Вы успешно заказали поставку товара.'
    traveler: '§b%VISITOR%§7 посетил(а) ваш музей, прибыль §6+%PRICE%'
    museum-teleported: '%VISITOR% принял ваше предложение. И посетил ваш музей.'
    not-in-museum: 'Вы не в музее...'
    welcome-gallery: 'Добро пожаловать в магазин!'
    welcome-home: 'Добро пожаловать в музей!'
    already-at-home: 'Вы уже в музее.'
    cannot-place: 'Вы не можете разместить данную постройку на этом блоке.'
    color-changed: 'Цвет витрины изменен.'
    owner-crash: 'UUID ты угадал, но тут есть защита от таких мудаков как ты...'
    placed: 'Постройка установлена!'
    destroyed: 'Постройка убрана в инвентарь!'
    non-root: 'Эта постройка вам не принадлежит.'
    treasure-item: '§6+%COST%$'
    reward: 'Вы нашли подарок! Вы получили %REWARD%!'
    levelup: 'Вы достигли §l§b%LEVEL% §7уровня! До следующего уровня осталось §l§b%EXP%§7 опыта.'
    excavationend: '§7Раскопки подошли к концу, сейчас вернем вас в музей!'
    findcopy: 'Вы нашли §b%NAME%, §7этот фрагмент - дубликат, его цена §l§6+%COST%.'
    findfragment: 'Вы откопали новый фрагмент: §b%NAME%§7!'
    freestand: 'Витрина освобождена!'
    standlocked: 'Вы не можете выбрать экспонат, он занят другой витриной.'
    standplaced: 'Экспонат поставлен на витрину!'
    nomoney: 'У вас не достаточно средств. 㬏'
    finally-buy: 'Вы приобрели новую постройку!'
    newpickaxe: 'Вы приобрели. Новое снаряжение!'
    newcollector: 'Вы приобрели %NAME% коллектор!'
    inviteyourself: 'Вы так одиноки? 㬚'
    invited: 'Приглашение отправлено.'
    invitefrom: 'Приглашение от %PLAYER%. [§6ПРИНЯТЬ§7]'
    playeroffline: 'Игрок не в сети. 㬏'
    museumtitlechange: 'Название музея изменено на "%TITLE%".'
    backtomuseum: '§7Вы вернулись в свой музей.'
    leavedfrommuseum: '§7%NAME% покинул ваш музей.'
    visitexcavation: 'Вы прибыли на §l§b%TITLE%.'
    visitaccepted: '%VISITOR% принял приглашение.'
    root-refuse: 'Вы не можете изменить название чужого музея!'